version: '2'

services:
   db:
     image: mysql:5.7
     container_name: wpdev_mysql
     volumes:
       - database:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     image: wordpress:latest
     container_name: wpdev_app
     volumes:
        - wordpress:/var/www/html
     depends_on:
        - db
     ports:
        - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
  wordpress:
    driver_opts:
      type: none
      device: /Users/chikuchu/docker/wordpress/app/
      o: bind
  database:
    driver_opts:
      type: none
      device: /Users/chikuchu/docker/wordpress/db/
      o: bind
